//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\Users\txt\Source\Repos\FBTC1\FBT.Generator\Parser\Grammar\FBT.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFBTListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class FBTBaseListener : IFBTListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.frostbiteType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrostbiteType([NotNull] FBTParser.FrostbiteTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.frostbiteType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrostbiteType([NotNull] FBTParser.FrostbiteTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.includeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIncludeBlock([NotNull] FBTParser.IncludeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.includeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIncludeBlock([NotNull] FBTParser.IncludeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclude([NotNull] FBTParser.IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclude([NotNull] FBTParser.IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeData([NotNull] FBTParser.TypeDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeData([NotNull] FBTParser.TypeDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeNamespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNamespace([NotNull] FBTParser.TypeNamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeNamespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNamespace([NotNull] FBTParser.TypeNamespaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeModule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeModule([NotNull] FBTParser.TypeModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeModule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeModule([NotNull] FBTParser.TypeModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassAttributes([NotNull] FBTParser.ClassAttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassAttributes([NotNull] FBTParser.ClassAttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeAttributes([NotNull] FBTParser.TypeAttributesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeAttributes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeAttributes([NotNull] FBTParser.TypeAttributesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeAttribute([NotNull] FBTParser.TypeAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeAttribute([NotNull] FBTParser.TypeAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.basicTypeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicTypeAttribute([NotNull] FBTParser.BasicTypeAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.basicTypeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicTypeAttribute([NotNull] FBTParser.BasicTypeAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.numeralTypeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeralTypeAttribute([NotNull] FBTParser.NumeralTypeAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.numeralTypeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeralTypeAttribute([NotNull] FBTParser.NumeralTypeAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeEnum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeEnum([NotNull] FBTParser.TypeEnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeEnum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeEnum([NotNull] FBTParser.TypeEnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumName([NotNull] FBTParser.EnumNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumName([NotNull] FBTParser.EnumNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumData([NotNull] FBTParser.EnumDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumData([NotNull] FBTParser.EnumDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValuePair([NotNull] FBTParser.EnumValuePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValuePair([NotNull] FBTParser.EnumValuePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeClass([NotNull] FBTParser.TypeClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeClass([NotNull] FBTParser.TypeClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassTypeName([NotNull] FBTParser.ClassTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassTypeName([NotNull] FBTParser.ClassTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classInherrits"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInherrits([NotNull] FBTParser.ClassInherritsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classInherrits"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInherrits([NotNull] FBTParser.ClassInherritsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classInherrit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInherrit([NotNull] FBTParser.ClassInherritContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classInherrit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInherrit([NotNull] FBTParser.ClassInherritContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeValueType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeValueType([NotNull] FBTParser.TypeValueTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeValueType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeValueType([NotNull] FBTParser.TypeValueTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.valueTypeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTypeIdentifier([NotNull] FBTParser.ValueTypeIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.valueTypeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTypeIdentifier([NotNull] FBTParser.ValueTypeIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.valueTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTypeName([NotNull] FBTParser.ValueTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.valueTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTypeName([NotNull] FBTParser.ValueTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.structureData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructureData([NotNull] FBTParser.StructureDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.structureData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructureData([NotNull] FBTParser.StructureDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberData([NotNull] FBTParser.MemberDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberData"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberData([NotNull] FBTParser.MemberDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberVisibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberVisibility([NotNull] FBTParser.MemberVisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberVisibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberVisibility([NotNull] FBTParser.MemberVisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberTypeName([NotNull] FBTParser.MemberTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberTypeName([NotNull] FBTParser.MemberTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberArrayType([NotNull] FBTParser.MemberArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberArrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberArrayType([NotNull] FBTParser.MemberArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberName([NotNull] FBTParser.MemberNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberName([NotNull] FBTParser.MemberNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberOffset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberOffset([NotNull] FBTParser.MemberOffsetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberOffset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberOffset([NotNull] FBTParser.MemberOffsetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typePrimitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypePrimitive([NotNull] FBTParser.TypePrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typePrimitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypePrimitive([NotNull] FBTParser.TypePrimitiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.primitiveTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveTypeName([NotNull] FBTParser.PrimitiveTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.primitiveTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveTypeName([NotNull] FBTParser.PrimitiveTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.numeral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeral([NotNull] FBTParser.NumeralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.numeral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeral([NotNull] FBTParser.NumeralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
