//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\Users\txt\Source\Repos\FBTC1\FBT.Generator\Parser\Grammar\FBT.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FBTParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IFBTListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.frostbiteType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrostbiteType([NotNull] FBTParser.FrostbiteTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.frostbiteType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrostbiteType([NotNull] FBTParser.FrostbiteTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.includeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeBlock([NotNull] FBTParser.IncludeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.includeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeBlock([NotNull] FBTParser.IncludeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclude([NotNull] FBTParser.IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclude([NotNull] FBTParser.IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeData([NotNull] FBTParser.TypeDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeData([NotNull] FBTParser.TypeDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNamespace([NotNull] FBTParser.TypeNamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNamespace([NotNull] FBTParser.TypeNamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeModule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeModule([NotNull] FBTParser.TypeModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeModule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeModule([NotNull] FBTParser.TypeModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassAttributes([NotNull] FBTParser.ClassAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassAttributes([NotNull] FBTParser.ClassAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAttributes([NotNull] FBTParser.TypeAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAttributes([NotNull] FBTParser.TypeAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAttribute([NotNull] FBTParser.TypeAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAttribute([NotNull] FBTParser.TypeAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.basicTypeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasicTypeAttribute([NotNull] FBTParser.BasicTypeAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.basicTypeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasicTypeAttribute([NotNull] FBTParser.BasicTypeAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.numeralTypeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeralTypeAttribute([NotNull] FBTParser.NumeralTypeAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.numeralTypeAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeralTypeAttribute([NotNull] FBTParser.NumeralTypeAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeEnum([NotNull] FBTParser.TypeEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeEnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeEnum([NotNull] FBTParser.TypeEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumName([NotNull] FBTParser.EnumNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumName([NotNull] FBTParser.EnumNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumData([NotNull] FBTParser.EnumDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumData([NotNull] FBTParser.EnumDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.enumValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValuePair([NotNull] FBTParser.EnumValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.enumValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValuePair([NotNull] FBTParser.EnumValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeClass([NotNull] FBTParser.TypeClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeClass([NotNull] FBTParser.TypeClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassTypeName([NotNull] FBTParser.ClassTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassTypeName([NotNull] FBTParser.ClassTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classInherrits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInherrits([NotNull] FBTParser.ClassInherritsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classInherrits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInherrits([NotNull] FBTParser.ClassInherritsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.classInherrit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInherrit([NotNull] FBTParser.ClassInherritContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.classInherrit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInherrit([NotNull] FBTParser.ClassInherritContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typeValueType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeValueType([NotNull] FBTParser.TypeValueTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typeValueType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeValueType([NotNull] FBTParser.TypeValueTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.valueTypeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTypeIdentifier([NotNull] FBTParser.ValueTypeIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.valueTypeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTypeIdentifier([NotNull] FBTParser.ValueTypeIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.valueTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTypeName([NotNull] FBTParser.ValueTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.valueTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTypeName([NotNull] FBTParser.ValueTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.structureData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructureData([NotNull] FBTParser.StructureDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.structureData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructureData([NotNull] FBTParser.StructureDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberData([NotNull] FBTParser.MemberDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberData([NotNull] FBTParser.MemberDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberVisibility([NotNull] FBTParser.MemberVisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberVisibility([NotNull] FBTParser.MemberVisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberTypeName([NotNull] FBTParser.MemberTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberTypeName([NotNull] FBTParser.MemberTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberArrayType([NotNull] FBTParser.MemberArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberArrayType([NotNull] FBTParser.MemberArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberName([NotNull] FBTParser.MemberNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberName([NotNull] FBTParser.MemberNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.memberOffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberOffset([NotNull] FBTParser.MemberOffsetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.memberOffset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberOffset([NotNull] FBTParser.MemberOffsetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.typePrimitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypePrimitive([NotNull] FBTParser.TypePrimitiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.typePrimitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypePrimitive([NotNull] FBTParser.TypePrimitiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.primitiveTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveTypeName([NotNull] FBTParser.PrimitiveTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.primitiveTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveTypeName([NotNull] FBTParser.PrimitiveTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FBTParser.numeral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumeral([NotNull] FBTParser.NumeralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FBTParser.numeral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumeral([NotNull] FBTParser.NumeralContext context);
}
